FROM node:18-alpine as angular

WORKDIR /app


COPY package*.json /app

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

FROM nginx:stable-alpine
VOLUME /var/cache/nginx

COPY --from=angular /app/dist/e-commerce /usr/share/nginx/html
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 4200

CMD ["nginx", "-g", "daemon off;"]
